version: '3.8'

services:
  app:
    build: .
    ports:
      - "3750:3000"
    volumes:
      - ./config:/app/config
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=production
    restart: unless-stopped